version: 2

models:
  # ==========================================================================
  # ECORIDE MODELS
  # ==========================================================================
  - name: customers
    description: "Cleaned customer data from EcoRide"
    columns:
      - name: id
        description: "Unique customer identifier"
        tests:
          - not_null
          - unique
      - name: first_name
        description: "Customer's first name"
      - name: email
        description: "Customer's email address"
        tests:
          - not_null
      - name: city
        description: "Customer's city"
      - name: state
        description: "Customer's state/province"
      - name: country
        description: "Customer's country"

  - name: sales
    description: "Vehicle sales transactions"
    columns:
      - name: id
        description: "Unique sale transaction identifier"
        tests:
          - not_null
          - unique
      - name: customer_id
        description: "Reference to customer"
        tests:
          - not_null
          - relationships:
              to: ref('customers')
              field: id
      - name: vehicle_id
        description: "Reference to vehicle"
      - name: sale_date
        description: "Date of the sale"
      - name: sale_price
        description: "Transaction amount"
      - name: payment_method
        description: "Payment method used"

  - name: vehicles
    description: "Vehicle catalog"
    columns:
      - name: id
        description: "Unique vehicle identifier"
        tests:
          - not_null
          - unique
      - name: model_name
        description: "Vehicle model name"
        tests:
          - accepted_values:
              values: ['EcoSprint', 'PowerRide', 'UrbanGlide', 'TerraCross', 'AeroFlow']
      - name: model_type
        description: "Vehicle type (Sedan, SUV, etc.)"
        tests:
          - accepted_values:
              values: ['Sedan', 'SUV', 'Hatchback', 'Coupe', 'Crossover']
      - name: color
        description: "Vehicle color"
      - name: year
        description: "Manufacturing year"

  - name: product_reviews
    description: "Customer product reviews"
    columns:
      - name: customer_id
        description: "Reference to customer who wrote the review"
        tests:
          - not_null
      - name: review_id
        description: "Unique review identifier"
        tests:
          - not_null
          - unique
      - name: review_date
        description: "Date the review was submitted"
      - name: rating
        description: "Rating (1-5 stars)"
      - name: review_text
        description: "Review content"
      - name: vehicle_model
        description: "Vehicle model being reviewed"

  # ==========================================================================
  # CHARGENET MODELS
  # ==========================================================================
  - name: charging_sessions
    description: "EV charging session logs"
    columns:
      - name: id
        description: "Unique session identifier"
        tests:
          - not_null
          - unique
      - name: station_id
        description: "Reference to charging station"
      - name: session_duration
        description: "Duration in minutes"
      - name: energy_consumed_kwh
        description: "Energy consumed in kWh"
      - name: charging_rate
        description: "Charging rate in kW"
      - name: cost
        description: "Session cost"
      - name: start_time
        description: "Session start timestamp"
      - name: end_time
        description: "Session end timestamp"

  - name: stations
    description: "Charging station locations"
    columns:
      - name: id
        description: "Unique station identifier"
        tests:
          - not_null
          - unique
      - name: address
        description: "Street address"
      - name: city
        description: "City"
      - name: state
        description: "State/province"
      - name: country
        description: "Country"
      - name: number_of_chargers
        description: "Number of charging ports"
      - name: operational_status
        description: "Current status (Active, Maintenance, etc.)"
      - name: station_type
        description: "Station type (Level 2, DC Fast, etc.)"

  # ==========================================================================
  # VEHICLE HEALTH MODELS
  # ==========================================================================
  - name: vehicle_health_logs
    description: "Vehicle diagnostics and maintenance history"
    columns:
      - name: vehicle_id
        description: "Vehicle identifier"
        tests:
          - not_null
      - name: model
        description: "Vehicle model"
      - name: manufacturing_year
        description: "Year of manufacture"
      - name: alerts
        description: "Active alerts/warnings"
      - name: maintenance_history
        description: "Maintenance record history"
