version: 2

sources:
  # Currently only customers data is available in MinIO (via Airbyte)
  # Other sources are defined for future use when data is ingested

  - name: ecoride_bronze
    database: minio
    schema: lakehouse."bronze.ecoride"."customers_ae0f9e2b-1483-4b02-98c1-bb27e5e135b4"
    tables:
      - name: customers
        identifier: data
      - name: vehicles
        description: "Not yet ingested - placeholder for future"
      - name: sales
        description: "Not yet ingested - placeholder for future"
      - name: product_reviews
        description: "Not yet ingested - placeholder for future"

  - name: chargenet_bronze
    database: minio
    schema: lakehouse."bronze.chargenet"
    tables:
      - name: stations
        description: "Not yet ingested - placeholder for future"
      - name: charging_sessions
        description: "Not yet ingested - placeholder for future"

  - name: vehicle_health_bronze
    database: minio
    schema: lakehouse."bronze.vehicle_health"
    tables:
      - name: logs
        description: "Not yet ingested - placeholder for future"