version: 2

sources:
  - name: ecoride_bronze
    database: minio
    schema: lakehouse."bronze.ecoride"
    tables:
      - name: customers
        identifier: customers_ae0f9e2b-1483-4b02-98c1-bb27e5e135b4.data