# Silver Layer Sources
# Points to Bronze Iceberg tables created by Airbyte
#
# Table naming: We use simple names (customers, sales, stations)
# These map to: catalog.bronze.{table_name}
#
# Airbyte adds metadata columns (_airbyte_*) which we exclude in Silver models.
# Silver models SELECT only business columns.

version: 2

sources:
  - name: bronze
    description: "Bronze Iceberg tables from Airbyte sync"
    database: catalog
    schema: bronze
    tables:
      # EcoRide domain
      - name: customers
        description: "Customer information (from ecoride_customers.csv)"
      - name: sales
        description: "Vehicle sales transactions (from ecoride_sales.csv)"
      - name: vehicles
        description: "Vehicle catalog (from ecoride_vehicles.csv)"
      - name: product_reviews
        description: "Customer product reviews (from ecoride_product_reviews.json)"

      # ChargeNet domain
      - name: stations
        description: "Charging station locations (from chargenet_stations.json)"
      - name: charging_sessions
        description: "Charging session logs (from chargenet_charging_sessions.json)"

      # Vehicle Health domain
      - name: vehicle_health
        description: "Vehicle diagnostics and maintenance (from vehicle_health_data.json)"
