# Silver Layer Sources
# Points to Bronze Iceberg tables in the Nessie catalog
#
# Path structure: catalog.bronze.{domain}_{table}
# Example: catalog.bronze.ecoride_customers
#
# These are proper Iceberg tables with:
# - Time travel (query historical data)
# - Schema evolution
# - ACID transactions
# - Metadata management

version: 2

sources:
  # ==========================================================================
  # ECORIDE SOURCES (Vehicle Sales)
  # Bronze Iceberg tables created from raw data
  # ==========================================================================
  - name: ecoride_bronze
    description: "EcoRide Bronze Iceberg tables"
    database: catalog
    schema: bronze
    tables:
      - name: ecoride_customers
        description: "Customer information"
      - name: ecoride_sales
        description: "Vehicle sales transactions"
      - name: ecoride_vehicles
        description: "Vehicle catalog"
      - name: ecoride_product_reviews
        description: "Customer product reviews"

  # ==========================================================================
  # CHARGENET SOURCES (Charging Infrastructure)
  # ==========================================================================
  - name: chargenet_bronze
    description: "ChargeNet Bronze Iceberg tables"
    database: catalog
    schema: bronze
    tables:
      - name: chargenet_stations
        description: "Charging station locations"
      - name: chargenet_charging_sessions
        description: "Charging session logs"

  # ==========================================================================
  # VEHICLE HEALTH SOURCES (Fleet Diagnostics)
  # ==========================================================================
  - name: vehicle_health_bronze
    description: "Vehicle health Bronze Iceberg tables"
    database: catalog
    schema: bronze
    tables:
      - name: vehicle_health_logs
        description: "Vehicle diagnostics and maintenance history"
