# dbt profile for Silver layer transformations
# Connects to Dremio SQL engine

silver:
  outputs:
    # Development target (Docker environment)
    dev:
      type: dremio
      software_host: "{{ env_var('DREMIO_HOST', 'dremio') }}"
      port: 9047
      user: "{{ env_var('DREMIO_USER', 'dremio') }}"
      password: "{{ env_var('DREMIO_PASSWORD', 'dremio123') }}"
      use_ssl: false
      threads: 1
      # Dremio spaces and storage
      dremio_space: lakehouse
      dremio_space_folder: silver
      object_storage_source: catalog
      object_storage_path: silver
  target: dev
    